kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:12
  user: node  
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-harvester-helmet
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: secret
name: docker_username
data: azdcbWQdfbE3VSytQhYc3/zfkVzxxrI0d5o2POH57S8iLxey0CAxHxjahw67rGjMV3U=
---
kind: secret
name: docker_password
data: Qhxv8Jz/9qTs9pYTXfs+rjJ1jj3UNlhtYeiDttY9pnhtAxwLeG8I3D6LHkZE3woHs+yrP/40Tv9iU5XGjXl6oZVgnseoVaO4xmMcUAQyHcOi+XWSBa9TBcScvgw=

